# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8987b5071eb5c74db0ea7dec94278a035bdcdae762d29304c94b646e533d34d3b9e241609e64ea2b6f8b7d4a696ac83ed2c734565b683e4a833892d4874b5b4f

test:
  secret_key_base: 8249d85bbbd1bb1d530634a1eb0de58915ca4f3e3f4b52f23615030123eba4bbef8c333f9ffb5d80bfacaace1b6213c30613e0f6c680d6791d05914d2f853c2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
